import 'dart:convert';
import 'dart:io';

import 'package:commute_guardian/data/station_repository.dart';
import 'package:commute_guardian/models/app_settings.dart';
import 'package:commute_guardian/services/announcement_templates.dart';
import 'package:commute_guardian/services/bundled_clips.dart';
import 'package:flutter_test/flutter_test.dart';

/// Guards `assets/clips/en-IN`, the clip pack that SHIPS INSIDE THE APP.
///
/// It is generated by tool/build_clip_assets.py from build/sarvam_clips, which
/// is not in the repository, so these are the only checks that run in CI. They
/// are cheap and they cover the two ways a pack goes wrong quietly: a manifest
/// that vouches for audio nobody bundled, and audio nobody can reach.
void main() {
  final dir = Directory('assets/clips/${AppLanguage.english.tag}');
  final manifest =
      jsonDecode(File('${dir.path}/manifest.json').readAsStringSync())
          as Map<String, dynamic>;
  final files = dir
      .listSync()
      .whereType<File>()
      .map((f) => f.uri.pathSegments.last)
      .toSet();

  test('the pack is the one language the picker offers', () {
    expect(AppLanguage.selectable, [AppLanguage.english]);
    expect(BundledClips.bundled, [AppLanguage.english]);
    expect(manifest, isNotEmpty);
  });

  test('EVERY VOUCHED CLIP IS ACTUALLY BUNDLED', () {
    // The failure this catches: a manifest copied from the WAV source while
    // an encode silently skipped a file. ClipLibrary would offer the clip,
    // find no file, and fall to TTS, so the ride still speaks. It would just
    // do it in the wrong voice at one station, forever, and nobody would know
    // which one.
    final missing = manifest.keys.where((k) => !files.contains('$k.m4a'));
    expect(missing, isEmpty);
  });

  test('and nothing unreachable is carried in the APK', () {
    // The other direction. A clip no manifest vouches for can never play, so
    // it is pure download size for every rider.
    final orphans = files
        .where((f) => f != 'manifest.json')
        .where((f) => !manifest.containsKey(f.replaceAll('.m4a', '')));
    expect(orphans, isEmpty);
  });

  test('THE PACK IS AAC, NOT WAV, WHICH IS WHY IT FITS AT ALL', () {
    // 891 WAV files are 128.7 MB and cannot go in an APK, which is why clip
    // delivery sat open in docs/adr/0001 from July and why a beta tester
    // could never be given a pack. At 32 kbps mono AAC the same pack is
    // 13.5 MB. A regenerated pack that lands back in WAV would quietly add
    // 115 MB to every rider's download.
    expect(files.where((f) => f.endsWith('.wav')), isEmpty);

    final bytes = dir
        .listSync()
        .whereType<File>()
        .fold<int>(0, (sum, f) => sum + f.lengthSync());
    expect(
      bytes,
      lessThan(25 * 1000 * 1000),
      reason: 'the pack measured 13.5 MB when this ceiling was set',
    );
  });

  test('A CLIP IS ONLY EVER PLAYED FOR A SENTENCE IT WAS CUT FROM', () {
    // The rule ClipLibrary enforces at runtime, checked here at build time
    // against the templates as they stand today. This is exactly how the
    // Hindi pack died: `f0ad04a` rewrote the templates, 864 clips became
    // stale, and nothing said so until somebody counted them.
    //
    // A mismatch is not a crash. The clip is refused and device TTS speaks
    // the same words, so this test fails long before a rider hears anything
    // wrong, which is the only time it is cheap to fix.
    final stations = StationRepository.parse(
      File(StationRepository.assetPath).readAsStringSync(),
    ).stationsById;

    // THREE RENDERERS, and the pack draws on all of them: ClipKind for the
    // ordinary announcements, WakeLine for the ladder, FixedLine for the two
    // sentences with no station name in them. A guard that knew only about
    // ClipKind would silently pass 378 wake clips it never checked, which is
    // the shape of every substring-guard bug this project has had.
    String? render(String suffix, String? stationName) {
      const language = AppLanguage.english;
      if (stationName == null) {
        final fixed = FixedLine.values.where((f) => f.fileSuffix == suffix);
        return fixed.isEmpty ? null : fixed.first.render(language: language);
      }
      final clip = ClipKind.values.where((k) => k.fileSuffix == suffix);
      if (clip.isNotEmpty) {
        return clip.first.render(stationName, language: language);
      }
      final wake = WakeLine.values.where((w) => w.fileSuffix == suffix);
      if (wake.isNotEmpty) {
        return wake.first.render(stationName, language: language);
      }
      return null;
    }

    final wrong = <String>[];
    for (final entry in manifest.entries) {
      final split = entry.key.lastIndexOf('__');
      final id = entry.key.substring(0, split);
      final suffix = entry.key.substring(split + 2);

      // `_fixed__` is the pack's own prefix for a sentence cut once per
      // language rather than once per station.
      final station = id == '_fixed' ? null : stations[id];
      if (id != '_fixed' && station == null) {
        wrong.add('${entry.key}: no such station');
        continue;
      }

      final rendered = render(suffix, station?.nameIn(AppLanguage.english));
      if (rendered == null) {
        wrong.add('${entry.key}: no template renders this clip kind');
      } else if (rendered != entry.value) {
        wrong.add('${entry.key}: ${entry.value} != $rendered');
      }
    }
    expect(wrong, isEmpty, reason: '${wrong.length} clips are stale');
  });
}
