import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter_test/flutter_test.dart';

/// Guards `assets/stations/mumbai_suburban.json`, which is generated by
/// `tool/build_stations.py`.
///
/// Every failed field ride on this project so far has traced back to bad station
/// coordinates: on 10 Jul 2026 three of four chain stations sat outside their own
/// geofence, so the ride recorded zero announcements with GPS, permissions and TTS
/// all working perfectly. These checks make that class of bug fail in CI instead of
/// on a train.
void main() {
  final raw = File('assets/stations/mumbai_suburban.json').readAsStringSync();
  final doc = jsonDecode(raw) as Map<String, dynamic>;
  final stations = (doc['stations'] as List).cast<Map<String, dynamic>>();
  final lines = (doc['lines'] as List).cast<Map<String, dynamic>>();
  final byId = {for (final s in stations) s['id'] as String: s};

  test('station ids are unique', () {
    expect(byId.length, stations.length);
  });

  test('station codes are unique', () {
    // The Indian Railways code is the real-world identity of a station, so two
    // entries sharing one means a single station has been split in two. That is
    // exactly how Jogeshwari got duplicated: OSM maps its Western and Harbour
    // platform groups as separate nodes 563m apart, both tagged ref=JOS, and a
    // name-based or id-based check cannot see the problem. This one can.
    final byCode = <String, String>{};
    for (final s in stations) {
      final code = s['code'] as String;
      expect(code, isNotEmpty, reason: '${s['id']} has no station code');
      expect(byCode, isNot(contains(code)),
          reason: '${s['id']} and ${byCode[code]} both claim code $code, so they '
              'are the same station. Merge them.');
      byCode[code] = s['id'] as String;
    }
  });

  test('every station has a name in English, Hindi and Marathi', () {
    for (final s in stations) {
      for (final key in ['name', 'nameHi', 'nameMr']) {
        expect(s[key], isA<String>().having((v) => v.isNotEmpty, 'non-empty', true),
            reason: '${s['id']} is missing $key');
      }
      // A Devanagari name that is really just the English name means the fallback
      // table in build_stations.py has a hole.
      for (final key in ['nameHi', 'nameMr']) {
        expect(s[key], isNot(s['name']),
            reason: '${s['id']} $key is not translated');
      }
    }
  });

  test('every station sits inside the Mumbai Suburban bounding box', () {
    for (final s in stations) {
      final lat = s['lat'] as double;
      final lng = s['lng'] as double;
      expect(lat, inInclusiveRange(18.6, 20.0), reason: '${s['id']} latitude');
      expect(lng, inInclusiveRange(72.6, 73.6), reason: '${s['id']} longitude');
    }
  });

  test('every line refers to stations that exist', () {
    for (final line in lines) {
      for (final id in (line['stationIds'] as List).cast<String>()) {
        expect(byId, contains(id), reason: 'line ${line['id']} refers to $id');
      }
    }
  });

  test('no line visits the same station twice', () {
    for (final line in lines) {
      final ids = (line['stationIds'] as List).cast<String>();
      expect(ids.toSet().length, ids.length,
          reason: 'line ${line['id']} has a duplicate station');
    }
  });

  test('adjacent stations on a line have non-overlapping geofences', () {
    for (final line in lines) {
      final ids = (line['stationIds'] as List).cast<String>();
      for (var i = 0; i < ids.length - 1; i++) {
        final a = byId[ids[i]]!;
        final b = byId[ids[i + 1]]!;
        final gap = _haversineM(a, b) -
            (a['radiusM'] as int) -
            (b['radiusM'] as int);
        expect(gap, greaterThan(0),
            reason: 'line ${line['id']}: ${ids[i]} and ${ids[i + 1]} have '
                'overlapping fences. A fix landing in both announces two stations '
                'at once and the chain cannot tell where the rider actually is.');
      }
    }
  });

  test('adjacent stations on a line are a plausible distance apart', () {
    for (final line in lines) {
      final ids = (line['stationIds'] as List).cast<String>();
      for (var i = 0; i < ids.length - 1; i++) {
        final d = _haversineM(byId[ids[i]]!, byId[ids[i + 1]]!);
        // Under 400m means two stations are pinned to the same spot; over 13km
        // means one is pinned to the wrong place or the line is mis-ordered.
        // The widest real gap on this network is Vangaon to Dahanu Road, 12.2km.
        expect(d, inInclusiveRange(400, 13000),
            reason: 'line ${line['id']}: ${ids[i]} to ${ids[i + 1]} is '
                '${d.round()}m');
      }
    }
  });

  test('co-located stations are only the known cross-line pairs', () {
    // Two stations sitting close together are fine when a line runs between them:
    // south Mumbai is dense, and Chinchpokli to Currey Road is a real 729m hop.
    // What is NOT fine is two stations close together that no line connects. That
    // signature means one station is mapped twice, or one has the wrong
    // coordinates.
    //
    // These four are genuine: distinct stations, distinct codes, that happen to sit
    // a few hundred metres apart where the Central and Western corridors run close.
    // Parel to Prabhadevi and Currey Road to Lower Parel are the well-known
    // foot-overbridge pairs. Contrast with Jogeshwari, which looked like this but
    // was one station duplicated: the 'station codes are unique' test is what tells
    // the two situations apart.
    //
    // CAUTION, and this bites in Phase 1: every one of these pairs has OVERLAPPING
    // geofences. Today that is harmless because each half sits on a different line
    // and no chain registers both. The moment a chain interchanges between Central
    // and Western at Dadar, which is one of the most common Mumbai commutes, both
    // Dadar fences arm at once and the rider gets a double announcement from an
    // ambiguous position. Fixing it properly means grouping platforms under a
    // complex id and registering at most one fence per complex. A station code
    // cannot express that, because DR and DDR really are two different stations.
    const knownComplexes = {
      'dadar|dadar_western',
      'parel|prabhadevi',
      'currey_road|lower_parel',
      'matunga|matunga_road',
    };

    final adjacent = <String>{};
    for (final line in lines) {
      final ids = (line['stationIds'] as List).cast<String>();
      for (var i = 0; i < ids.length - 1; i++) {
        adjacent.add(([ids[i], ids[i + 1]]..sort()).join('|'));
      }
    }

    for (var i = 0; i < stations.length; i++) {
      for (var j = i + 1; j < stations.length; j++) {
        final a = stations[i];
        final b = stations[j];
        final d = _haversineM(a, b);
        if (d >= 800) continue;
        final pair = ([a['id'] as String, b['id'] as String]..sort()).join('|');
        if (adjacent.contains(pair)) continue;
        expect(knownComplexes, contains(pair),
            reason: '${a['id']} and ${b['id']} are ${d.round()}m apart but no line '
                'connects them. Either they are the same station mapped twice, or '
                'one has the wrong coordinates.');
      }
    }
  });

  test('every line is a real line, not a hand-authored ride chain', () {
    // `harbour_ride_kalyan_digha` used to live here: the Kalyan -> Digha field
    // ride, hand-authored as a fake "line" because nothing could derive it.
    // JourneyPlanner derives it now (journey_planner_test asserts it reproduces
    // that exact chain), so a ride chain in this file is a regression: it means
    // someone hardcoded a route instead of planning it.
    for (final line in lines) {
      expect(
        line['id'] as String,
        isNot(startsWith('ride_')),
        reason: 'ride chains belong in JourneyPlanner, not in the line data',
      );
      expect(
        line['name'] as String,
        isNot(startsWith('Ride:')),
        reason: 'ride chains belong in JourneyPlanner, not in the line data',
      );
    }
  });

  test('every line can be spoken and lists its interchange platforms', () {
    for (final line in lines) {
      expect(line['shortName'], isNotEmpty,
          reason: '${line['id']} has no spoken short name');
      // Platforms are sparse by design, but every station they name must exist.
      for (final stationId in (line['platforms'] as Map).keys) {
        expect(byId.containsKey(stationId), isTrue,
            reason: '${line['id']} names a platform at unknown station $stationId');
        expect((line['stationIds'] as List), contains(stationId),
            reason: '${line['id']} names a platform at $stationId, '
                'which is not on that line');
      }
    }
  });
}

double _haversineM(Map<String, dynamic> a, Map<String, dynamic> b) {
  const earthRadiusM = 6371000.0;
  final lat1 = (a['lat'] as double) * pi / 180;
  final lat2 = (b['lat'] as double) * pi / 180;
  final dLat = lat2 - lat1;
  final dLng = ((b['lng'] as double) - (a['lng'] as double)) * pi / 180;
  final h = pow(sin(dLat / 2), 2) +
      cos(lat1) * cos(lat2) * pow(sin(dLng / 2), 2);
  return 2 * earthRadiusM * asin(sqrt(h));
}
