import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/services.dart' show rootBundle;

import '../models/line.dart';
import '../models/station.dart';
import '../services/journey_planner.dart';

/// Loads the bundled Mumbai Suburban station/line data.
///
/// The asset is generated by `tool/build_stations.py` from OpenStreetMap.
/// Edit that script and rerun it, never the JSON by hand.
class StationRepository {
  StationRepository._({
    required this.stationsById,
    required this.linesById,
    required this.throughServices,
  });

  final Map<String, Station> stationsById;
  final Map<String, Line> linesById;

  /// Pairs of line ids one physical train continues across. See
  /// [JourneyPlanner.throughServices].
  final List<List<String>> throughServices;

  /// Plans rides over this network. See [JourneyPlanner].
  late final JourneyPlanner planner = JourneyPlanner(
    stationsById: stationsById,
    linesById: linesById,
    throughServices: throughServices,
  );

  static const assetPath = 'assets/stations/mumbai_suburban.json';

  static Future<StationRepository> load() async =>
      StationRepository.parse(await rootBundle.loadString(assetPath));

  /// Builds a repository from the raw asset JSON. Separate from [load] so callers
  /// that already have the bytes (a test reading the file straight off disk) do
  /// not have to go through the asset bundle to get one.
  factory StationRepository.parse(String raw) {
    final json = jsonDecode(raw) as Map<String, dynamic>;

    final stations = (json['stations'] as List)
        .cast<Map<String, dynamic>>()
        .map(Station.fromJson);
    final lines =
        (json['lines'] as List).cast<Map<String, dynamic>>().map(Line.fromJson);

    return StationRepository._(
      stationsById: {for (final s in stations) s.id: s},
      linesById: {for (final l in lines) l.id: l},
      throughServices: [
        for (final pair in (json['throughServices'] as List? ?? const []))
          (pair as List).cast<String>(),
      ],
    );
  }

  Station station(String id) {
    final station = stationsById[id];
    if (station == null) {
      throw ArgumentError('Unknown station id: $id');
    }
    return station;
  }

  /// The station closest to a position, used to default a ride's origin to where
  /// the rider is actually standing. Straight-line distance: at Mumbai station
  /// spacing (roughly 1 to 2 km) the nearest station by air is the nearest one on
  /// foot, and picking the wrong one is a dropdown away from being corrected.
  Station nearestStation(double lat, double lng) {
    Station? best;
    var bestDistance = double.infinity;
    for (final station in stationsById.values) {
      final distance = _distanceM(lat, lng, station.lat, station.lng);
      if (distance < bestDistance) {
        bestDistance = distance;
        best = station;
      }
    }
    return best!;
  }

  /// Metres between [station] and a position. Used to sanity-check that a fix is
  /// anywhere near the network before trusting the station it names as nearest.
  double distanceToM(Station station, double lat, double lng) =>
      _distanceM(lat, lng, station.lat, station.lng);

  static double _distanceM(
    double lat1,
    double lng1,
    double lat2,
    double lng2,
  ) {
    const earthRadiusM = 6371000.0;
    final dLat = _toRad(lat2 - lat1);
    final dLng = _toRad(lng2 - lng1);
    final a = math.sin(dLat / 2) * math.sin(dLat / 2) +
        math.cos(_toRad(lat1)) *
            math.cos(_toRad(lat2)) *
            math.sin(dLng / 2) *
            math.sin(dLng / 2);
    return earthRadiusM * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a));
  }

  static double _toRad(double deg) => deg * math.pi / 180.0;
}
