import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

import '../models/line.dart';
import '../models/station.dart';
import '../services/journey_planner.dart';

/// Loads the bundled Mumbai Suburban station/line data.
///
/// The asset is generated by `tool/build_stations.py` from OpenStreetMap.
/// Edit that script and rerun it, never the JSON by hand.
class StationRepository {
  StationRepository._({required this.stationsById, required this.linesById});

  final Map<String, Station> stationsById;
  final Map<String, Line> linesById;

  /// Plans rides over this network. See [JourneyPlanner].
  late final JourneyPlanner planner =
      JourneyPlanner(stationsById: stationsById, linesById: linesById);

  static const _assetPath = 'assets/stations/mumbai_suburban.json';

  static Future<StationRepository> load() async {
    final raw = await rootBundle.loadString(_assetPath);
    final json = jsonDecode(raw) as Map<String, dynamic>;

    final stations = (json['stations'] as List)
        .cast<Map<String, dynamic>>()
        .map(Station.fromJson);
    final lines =
        (json['lines'] as List).cast<Map<String, dynamic>>().map(Line.fromJson);

    return StationRepository._(
      stationsById: {for (final s in stations) s.id: s},
      linesById: {for (final l in lines) l.id: l},
    );
  }

  Station station(String id) {
    final station = stationsById[id];
    if (station == null) {
      throw ArgumentError('Unknown station id: $id');
    }
    return station;
  }
}
