"""Encode a Sarvam WAV clip pack into the bundled AAC asset pack.

WHY THIS EXISTS: raw WAV en-IN is 891 files and 128.7 MB, which is why clip
delivery sat open in docs/adr/0001 since July. 32 kbps mono AAC measures 9.5x
smaller, which puts a language pack near 13.5 MB and inside the APK outright:
no asset pack, no download, no server, and a beta tester who has never seen
adb still gets the Sarvam voice.

Input  build/sarvam_clips/{tag}   (WAV, generated by tool/build_sarvam_clips.py)
Output assets/clips/{tag}         (M4A + manifest.json, bundled by pubspec.yaml)

NEVER HAND-EDIT THE OUTPUT. Re-run this instead, the same rule the station
JSON and the app icons live under.

The manifest is copied, not regenerated: it records the exact sentence each
clip was cut from, and re-deriving it here would defeat the byte-identical
check it exists to enforce (see lib/services/clip_library.dart). Keys carry no
file extension, so the WAV-to-M4A change does not touch it.

Clips that measure too long for their sentence are DROPPED from the copy. A
key absent from the manifest is refused by ClipLibrary and falls to device TTS
with the identical sentence, so dropping one costs that line its nicer voice
and costs the rider nothing. That is the fix for a bad clip that does not need
the Sarvam API.
"""

import json
import math
import shutil
import statistics
import subprocess
import sys
import wave
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

BITRATE = "32k"
REPO = Path(__file__).resolve().parent.parent

# HOW MUCH AUDIO MAY EXCEED THE SENTENCE, in seconds. The 16 Aug 2026 bad clip
# (vidyavihar__approach, heard as "gibberish after Vidyavihar" on both legs of
# the CSMT ride) carried +1.97 s. Nothing under +1.0 s has ever been reported
# as wrong. The cost of being strict is one line of TTS, so err strict.
MAX_EXCESS_S = 1.0

# A pack where this many clips measure bad is a broken pack, not a few bad
# cuts, and it should stop the build rather than quietly ship as a stub.
MAX_DROPPED = 25


def durations(src_dir: Path, manifest: dict) -> dict:
    """Seconds of audio per key, straight out of the wav header."""
    out = {}
    for key in manifest:
        with wave.open(str(src_dir / f"{key}.wav")) as handle:
            out[key] = handle.getnframes() / handle.getframerate()
    return out


def excesses(manifest: dict, seconds: dict) -> dict:
    """Seconds of audio each clip carries beyond what its sentence predicts.

    WHY A PREDICTION AND NOT A MEAN: duration tracks sentence length, and both
    the kind and the station name move that length, so a clip can sit at twice
    its kind's mean and be perfectly good ("Chhatrapati Shivaji Maharaj
    Terminus" is not "Kopar"). The 16 Aug sweep used a per-kind mean, swept
    only the approach clips, and found one bad clip of the nine here.

    Two steps. Fit duration against character count across the whole pack,
    then subtract each KIND's median residual. The second step matters: the
    overshoot sentence carries a mid-sentence pause ("It is alright.") that
    the character count cannot see, so overshoot clips sit +0.53 s above the
    global line as a body and four ordinary ones were flagged without it.

    Both steps use every clip including the bad ones. That is deliberate: a
    fit recomputed after exclusion tightens its own spread and starts flagging
    the clips next in line, which is exactly what happened on the first run.
    """
    keys = list(manifest)
    chars = [len(manifest[k]) for k in keys]
    secs = [seconds[k] for k in keys]
    mean_chars = statistics.mean(chars)
    mean_secs = statistics.mean(secs)
    slope = sum(
        (c - mean_chars) * (s - mean_secs) for c, s in zip(chars, secs)
    ) / sum((c - mean_chars) ** 2 for c in chars)
    intercept = mean_secs - slope * mean_chars

    residual = {k: seconds[k] - (intercept + slope * len(manifest[k])) for k in keys}
    by_kind = defaultdict(list)
    for key, value in residual.items():
        by_kind[key.split("__", 1)[1]].append(value)
    offset = {kind: statistics.median(v) for kind, v in by_kind.items()}
    return {k: residual[k] - offset[k.split("__", 1)[1]] for k in keys}


def encode(src: Path, dst: Path) -> None:
    subprocess.run(
        [
            "ffmpeg", "-nostdin", "-loglevel", "error", "-y",
            "-i", str(src),
            "-c:a", "aac", "-b:a", BITRATE, "-ac", "1",
            str(dst),
        ],
        check=True,
    )


def main(tag: str) -> int:
    src_dir = REPO / "build" / "sarvam_clips" / tag
    out_dir = REPO / "assets" / "clips" / tag
    if not (src_dir / "manifest.json").is_file():
        print(f"no manifest in {src_dir}, refusing to build a pack", file=sys.stderr)
        return 1

    manifest = json.loads((src_dir / "manifest.json").read_text(encoding="utf-8"))
    missing = [k for k in manifest if not (src_dir / f"{k}.wav").is_file()]
    if missing:
        print(f"manifest vouches for {len(missing)} clips with no wav: "
              f"{', '.join(missing[:5])}", file=sys.stderr)
        return 1

    seconds = durations(src_dir, manifest)
    excess = excesses(manifest, seconds)
    dropped = sorted(
        (k for k, e in excess.items() if e > MAX_EXCESS_S),
        key=lambda k: -excess[k],
    )
    kept = {k: v for k, v in manifest.items() if k not in set(dropped)}

    if len(dropped) > MAX_DROPPED:
        print(f"{len(dropped)} clips measure too long, over the {MAX_DROPPED} "
              f"limit. This pack is broken, not merely imperfect.", file=sys.stderr)
        return 1

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)
    with ThreadPoolExecutor(max_workers=8) as pool:
        list(pool.map(
            lambda k: encode(src_dir / f"{k}.wav", out_dir / f"{k}.m4a"), kept
        ))
    (out_dir / "manifest.json").write_text(
        json.dumps(kept, ensure_ascii=False, indent=1, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    total = sum(f.stat().st_size for f in out_dir.iterdir())
    source = sum(f.stat().st_size for f in src_dir.glob("*.wav"))
    print(f"{tag}: {len(kept)} clips, {total / 1e6:.1f} MB "
          f"(from {source / 1e6:.1f} MB, {source / total:.1f}x smaller)")
    print(f"dropped {len(dropped)} clip(s) over +{MAX_EXCESS_S:.1f}s. "
          f"Each falls back to device TTS with the identical sentence.")
    for key in dropped:
        print(f"  +{excess[key]:.2f}s  {seconds[key]:5.2f}s  {key}")
    print("Re-cut these with tool/build_sarvam_clips.py to win them back.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else "en-IN"))
